title: <p align="center"> Akshay Kadam </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="docs/Akshay_Kadam_Resume.pdf">Resume</a>
  <a href="https://www.linkedin.com/akshayvmkadam">LinkedIn</a>
  
  <br>
  A qualified and accomplished professional having robust technical expertise converged with leadership
  excellence experience of 7.5 years in the software industry.
  </br>
  </p>


theme: jekyll-theme-minimal
